version: '3.9'

services:
  app:
    image: mybuttonproject:latest_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./mybuttonproject.api:/app/mybuttonproject.api
      - ./mybuttonproject.web:/app/mybuttonproject.web